CREATE TABLE AMIGO(
    AID INTEGER NOT NULL CONSTRAINT PK_AMIGO PRIMARY KEY,
    ANOME VARCHAR2(50),
    SEXO CHAR,
    IDADE  INTEGER);
    
CREATE TABLE PRESENTE(
    PID INTEGER NOT NULL CONSTRAINT PK_PRESENTE PRIMARY KEY,
    PDESCRICAO VARCHAR2(50),
    PVALOR NUMBER(5,2));
    
CREATE TABLE LISTAPRESENTE(
    ID_LISTAPRESENTES INTEGER NOT NULL CONSTRAINT PK_LISTAPRESENTE PRIMARY KEY,
    AID INTEGER,
    PID INTEGER,
    PREFERENCIA INTEGER,
    CONSTRAINT FK_LISTA_AMIGO FOREIGN KEY (AID) REFERENCES AMIGO,
    CONSTRAINT FK_LISTA_PRESENTE FOREIGN KEY (PID) REFERENCES PRESENTE);
    
CREATE TABLE AMIGOSECRETO(
    ID_AMIGOSECRETO INTEGER NOT NULL CONSTRAINT PK_AMIGOSECRETO PRIMARY KEY,
    AID INTEGER,
    AID_AMIGO INTEGER,
    PID_RECEBIDO INTEGER,
    CONSTRAINT FK_AMIGO FOREIGN KEY (AID) REFERENCES AMIGO,
    CONSTRAINT FK_AMIGOSECRETO FOREIGN KEY (AID_AMIGO) REFERENCES AMIGO,
    CONSTRAINT FK_PRESENTE FOREIGN KEY (PID_RECEBIDO) REFERENCES PRESENTE);